### ISSUE TITLE
Cannot read property 'vaultRoot' of undefined in Node Environment

### ISSUE THREAD

**Issue by lsbyerley** [starkware-libs/starkex-js#11]
**Describe the bug**
Runtime error when using the getBatchIds() function

**To Reproduce**

```javascript
const StarkExAPI = require('@starkware-industries/starkex-js/node');
// (this actually doesn't work either, i have to use: 
// const StarkExAPI = require('../node_modules/@starkware-industries/starkex-js/dist/node');

const batchIds = await starkExAPI.feederGateway.getBatchIds();

// TypeError: Cannot read property 'vaultRoot' of undefined
```

**Expected behavior**
Batch ID's returned and no error

**Desktop (please complete the following information):**

- OS: macOs Catalina 10.15.7
- Node v14.17.6

**Comment by dan-ziv** [comment]
Hi @lsbyerley,
Thanks for reporting this issue!

I guess this error is raised since `getBatchIds` API accepts request object of the form:
```javascript
interface BatchIdsRequest {
  vaultRoot: string;
  orderRoot: string;
  sequenceNumber: number;
}
```
You can TAL also in the offical docs:
https://starkware.co/StarkExRESTAPI/feeder_gateway.html#services.starkex.feeder_gateway.feeder_gateway.FeederGateway.get_batch_ids
or in the package docs:
https://github.com/starkware-libs/starkex-js/blob/master/docs/classes/FeederGateway.md#getbatchids

Try to send this request as documented and LMK if you faced any issue.

**Comment by lsbyerley** [comment]
Hey @dan-ziv thank you for the response. I see that it accepts a batchId based on the official doc link. I was thrown off by the example in the readme of this repo https://github.com/starkware-libs/starkex-js#public-feedergateway-feedergateway

**Comment by dan-ziv** [comment]
Thanks for that!
We'll fix the README file.
